Repository beRajeevKumar/Frontend_Mentor, pull requests merged in 2024-10, with the labels that each got.

#16 #Add Code_Of_Conduct File
  Code_Of_Conduct.md
Labels: good first issue, hacktoberfest, gssoc-ext, gssoc

#29 Enhance title of website
  index.html
  script.js
  style.css
Labels: enhancement, good first issue, hacktoberfest, gssoc-ext, gssoc, level1

#131 Added a Weather App #69
  23-Weather-App/404.png
  23-Weather-App/clear.png
  23-Weather-App/cloud.png
  23-Weather-App/design/desktop-design.jpg
  23-Weather-App/icon.png
  23-Weather-App/index.html
  23-Weather-App/mist.png
  23-Weather-App/rain.png
  23-Weather-App/script.js
  23-Weather-App/snow.png
  23-Weather-App/style.css
  script.js
Labels: enhancement, good first issue, hacktoberfest, gssoc-ext, gssoc, level2, hacktoberfest-accepted

#179 chore: change 'summery' to 'summary'
  11-Order-summary-component/.gitignore
  11-Order-summary-component/README-template.md
  11-Order-summary-component/README.md
  11-Order-summary-component/design/active-states.jpg
  11-Order-summary-component/design/desktop-design.jpg
  11-Order-summary-component/design/desktop-preview.jpg
  11-Order-summary-component/design/mobile-design.jpg
  11-Order-summary-component/images/favicon-32x32.png
  11-Order-summary-component/images/icon-music.svg
  11-Order-summary-component/images/illustration-hero.svg
  11-Order-summary-component/images/pattern-background-desktop.svg
  11-Order-summary-component/images/pattern-background-mobile.svg
  11-Order-summary-component/index.html
  11-Order-summary-component/style-guide.md
  11-Order-summary-component/style.css
  script.js
Labels: hacktoberfest, gssoc-ext, gssoc, level1, hacktoberfest-accepted

#202 conflicts resolved and issue resolved #14
  index.html
  style.css
Labels: hacktoberfest, gssoc-ext, gssoc, level1, hacktoberfest-accepted

#337 added card design perfectly ,changes navbar , changes hover effect on card , changes color
  01-Community-Card/index.html
  index.html
  style.css
Labels: enhancement, good first issue, hacktoberfest, gssoc-ext, gssoc, level1, hacktoberfest-accepted

#100 #50 Responsive Issues of Project 15
  15-Article-Preview/style.css
Labels: enhancement, good first issue, hacktoberfest, gssoc-ext, gssoc, level1, hacktoberfest-accepted

#323 Updated MIT LICENSE in README.md file
  .vscode/settings.json
  README.md
  index.html
  style.css
Labels: bug, good first issue, hacktoberfest, gssoc-ext, gssoc, level1, hacktoberfest-accepted

#246 UI enhancement in Signup and login Pages
  f1.png
  index.html
  login.avif
  login.html
  login.jpeg
  login.jpg
  login.png
  login.webp
  signUp.css
  signUp.html
  signup.jpg
  signup.png
  signup.webp
Labels: enhancement, hacktoberfest, gssoc-ext, gssoc, level3, hacktoberfest-accepted

#383 [BUG] Login Page Not Found - 404 Error on Click, Create login page
  README.md
Labels: good first issue, hacktoberfest, gssoc-ext, gssoc, level1, hacktoberfest-accepted

#448 Revert "Added a Html and css to resolve the issue on testimonial grid section."
  20-testimonials-grid-section/index.html
  20-testimonials-grid-section/style.css
Labels: bug, good first issue, hacktoberfest, gssoc-ext, gssoc, level1, hacktoberfest-accepted

#443 Update style.css
  style.css
Labels: bug, good first issue, hacktoberfest, gssoc-ext, gssoc, level1, hacktoberfest-accepted

#426 Make Rating Page Dynamic by Changing Number of Stars Based on Selection
  05-intractive-rating/images/grey-star.svg
  05-intractive-rating/index.html
  05-intractive-rating/script.js
  05-intractive-rating/style.css
  signUp.css
  signUp.html
Labels: enhancement, good first issue, hacktoberfest, gssoc-ext, gssoc, level1, hacktoberfest-accepted

#511 Added Guess the number Game
  26-guess-the-number-game/README.md
  26-guess-the-number-game/design/correct.png
  26-guess-the-number-game/design/desktop-design.jpg
  26-guess-the-number-game/design/easy-1.png
  26-guess-the-number-game/design/hard-1.png
  26-guess-the-number-game/design/high.png
  26-guess-the-number-game/design/loose.png
  26-guess-the-number-game/design/low.png
  26-guess-the-number-game/img/game.png
  26-guess-the-number-game/index.html
  26-guess-the-number-game/index.js
  26-guess-the-number-game/sounds/error.mp3
  26-guess-the-number-game/sounds/music1.wav
  26-guess-the-number-game/sounds/music2.wav
  26-guess-the-number-game/sounds/music3.wav
  26-guess-the-number-game/sounds/music4.wav
  26-guess-the-number-game/style.css
  script.js
Labels: enhancement, hacktoberfest, gssoc-ext, gssoc, level2, hacktoberfest-accepted

#161 Add mini chabot to the website
  .env.example
  boy.png
  chatbot.gif
  chatbot.html
  index.html
Labels: enhancement, hacktoberfest, gssoc-ext, gssoc, level3, hacktoberfest-accepted

#514 Revert "Add mini chabot to the website"
  .env.example
  boy.png
  chatbot.gif
  chatbot.html
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#515 Revert "Issue #124 resolved : Fixed three cards margin and responsive issues"
  10-three-column-card/style.css
Labels: hacktoberfest, hacktoberfest-accepted

#494 Create greeting.yml
  .github/workflows/greeting.yml
Labels: good first issue, hacktoberfest, gssoc-ext, gssoc, level1, hacktoberfest-accepted

#330 Fixed card 11 Order Summary Component (Issue #327)
  script.js
Labels: good first issue, hacktoberfest, gssoc-ext, gssoc, level1, hacktoberfest-accepted

#423 Fix Image Visibility and Alignment of div of "Sign Up" page
  signUp.css
  signUp.html
Labels: bug, good first issue, hacktoberfest, gssoc-ext, gssoc, level1, hacktoberfest-accepted

#544 Add a Responsive Shoe Website
  26-shoe-website/design/desktop-design.jpg
  26-shoe-website/image/bg1.png
  26-shoe-website/image/facebook.png
  26-shoe-website/image/gir_dp2.jpg
  26-shoe-website/image/gir_dp3.jpg
  26-shoe-website/image/girl_dp1.jpg
  26-shoe-website/image/google.png
  26-shoe-website/image/loging_bg.png
  26-shoe-website/image/logo.png
  26-shoe-website/image/logshoes.png
  26-shoe-website/image/man_dp1.jpg
  26-shoe-website/image/man_dp2.jpg
  26-shoe-website/image/man_dp3.jpg
  26-shoe-website/image/nike.png
  26-shoe-website/image/red_shoes1.png
  26-shoe-website/image/red_shoes2.png
  26-shoe-website/image/red_shoes3.png
  26-shoe-website/image/red_shoes4.png
  26-shoe-website/image/shoes.png
  26-shoe-website/image/shoes1.png
  26-shoe-website/image/shoes2.png
  26-shoe-website/image/shoes3.png
  26-shoe-website/image/shoes4.png
  26-shoe-website/image/shoes5.png
  26-shoe-website/image/shoes6.png
  26-shoe-website/image/shoes7.png
  26-shoe-website/image/shoes8.png
  26-shoe-website/image/twitter.png
  26-shoe-website/index.html
  26-shoe-website/style.css
  README.md
  script.js
Labels: enhancement, hacktoberfest, gssoc-ext, gssoc, level3, hacktoberfest-accepted

#552 Update README.md added Stargazers and Forkers section
  README.md
Labels: enhancement, hacktoberfest, gssoc-ext, gssoc, level1, hacktoberfest-accepted

#462 Favicon added to the website
  01-Community-Card/images/favlogo.png
  index.html
Labels: good first issue, hacktoberfest, gssoc-ext, gssoc, level1, hacktoberfest-accepted

#587 Add Tic tac Toe project
  30-currency-converter/codes.js
  30-currency-converter/design/desktop-design.jpg
  30-currency-converter/index.html
  30-currency-converter/learning.txt
  30-currency-converter/script.js
  30-currency-converter/style.css
  31-tic-tac-toe/app.js
  31-tic-tac-toe/design/desktop-design.jpg
  31-tic-tac-toe/index.html
  31-tic-tac-toe/style.css
  script.js
Labels: enhancement, hacktoberfest, gssoc-ext, gssoc, level2, hacktoberfest-accepted
